//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestWinForm.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.QuestWebServiceSoap")]
    public interface QuestWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name Title from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddQuest", ReplyAction="*")]
        QuestWinForm.ServiceReference1.AddQuestResponse AddQuest(QuestWinForm.ServiceReference1.AddQuestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddQuest", ReplyAction="*")]
        System.Threading.Tasks.Task<QuestWinForm.ServiceReference1.AddQuestResponse> AddQuestAsync(QuestWinForm.ServiceReference1.AddQuestRequest request);
        
        // CODEGEN: Generating message contract since element name Username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddUser", ReplyAction="*")]
        QuestWinForm.ServiceReference1.AddUserResponse AddUser(QuestWinForm.ServiceReference1.AddUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddUser", ReplyAction="*")]
        System.Threading.Tasks.Task<QuestWinForm.ServiceReference1.AddUserResponse> AddUserAsync(QuestWinForm.ServiceReference1.AddUserRequest request);
        
        // CODEGEN: Generating message contract since element name ShowQuestResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowQuest", ReplyAction="*")]
        QuestWinForm.ServiceReference1.ShowQuestResponse ShowQuest(QuestWinForm.ServiceReference1.ShowQuestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowQuest", ReplyAction="*")]
        System.Threading.Tasks.Task<QuestWinForm.ServiceReference1.ShowQuestResponse> ShowQuestAsync(QuestWinForm.ServiceReference1.ShowQuestRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckUser", ReplyAction="*")]
        QuestWinForm.ServiceReference1.CheckUserResponse CheckUser(QuestWinForm.ServiceReference1.CheckUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckUser", ReplyAction="*")]
        System.Threading.Tasks.Task<QuestWinForm.ServiceReference1.CheckUserResponse> CheckUserAsync(QuestWinForm.ServiceReference1.CheckUserRequest request);
        
        // CODEGEN: Generating message contract since element name ShowUserResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowUser", ReplyAction="*")]
        QuestWinForm.ServiceReference1.ShowUserResponse ShowUser(QuestWinForm.ServiceReference1.ShowUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowUser", ReplyAction="*")]
        System.Threading.Tasks.Task<QuestWinForm.ServiceReference1.ShowUserResponse> ShowUserAsync(QuestWinForm.ServiceReference1.ShowUserRequest request);
        
        // CODEGEN: Generating message contract since element name ShowLeaderboardResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowLeaderboard", ReplyAction="*")]
        QuestWinForm.ServiceReference1.ShowLeaderboardResponse ShowLeaderboard(QuestWinForm.ServiceReference1.ShowLeaderboardRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowLeaderboard", ReplyAction="*")]
        System.Threading.Tasks.Task<QuestWinForm.ServiceReference1.ShowLeaderboardResponse> ShowLeaderboardAsync(QuestWinForm.ServiceReference1.ShowLeaderboardRequest request);
        
        // CODEGEN: Generating message contract since element name ShowQuestBoardResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowQuestBoard", ReplyAction="*")]
        QuestWinForm.ServiceReference1.ShowQuestBoardResponse ShowQuestBoard(QuestWinForm.ServiceReference1.ShowQuestBoardRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowQuestBoard", ReplyAction="*")]
        System.Threading.Tasks.Task<QuestWinForm.ServiceReference1.ShowQuestBoardResponse> ShowQuestBoardAsync(QuestWinForm.ServiceReference1.ShowQuestBoardRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AcceptQuest", ReplyAction="*")]
        void AcceptQuest(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AcceptQuest", ReplyAction="*")]
        System.Threading.Tasks.Task AcceptQuestAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Reward", ReplyAction="*")]
        void Reward(int id, int tokens, int badges);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Reward", ReplyAction="*")]
        System.Threading.Tasks.Task RewardAsync(int id, int tokens, int badges);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddQuestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddQuest", Namespace="http://tempuri.org/", Order=0)]
        public QuestWinForm.ServiceReference1.AddQuestRequestBody Body;
        
        public AddQuestRequest() {
        }
        
        public AddQuestRequest(QuestWinForm.ServiceReference1.AddQuestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddQuestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Title;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Description;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Tokens;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int Badges;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int CreatorId;
        
        public AddQuestRequestBody() {
        }
        
        public AddQuestRequestBody(string Title, string Description, int Tokens, int Badges, int CreatorId) {
            this.Title = Title;
            this.Description = Description;
            this.Tokens = Tokens;
            this.Badges = Badges;
            this.CreatorId = CreatorId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddQuestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddQuestResponse", Namespace="http://tempuri.org/", Order=0)]
        public QuestWinForm.ServiceReference1.AddQuestResponseBody Body;
        
        public AddQuestResponse() {
        }
        
        public AddQuestResponse(QuestWinForm.ServiceReference1.AddQuestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddQuestResponseBody {
        
        public AddQuestResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddUser", Namespace="http://tempuri.org/", Order=0)]
        public QuestWinForm.ServiceReference1.AddUserRequestBody Body;
        
        public AddUserRequest() {
        }
        
        public AddUserRequest(QuestWinForm.ServiceReference1.AddUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Tokens;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int Badges;
        
        public AddUserRequestBody() {
        }
        
        public AddUserRequestBody(string Username, string Password, int Tokens, int Badges) {
            this.Username = Username;
            this.Password = Password;
            this.Tokens = Tokens;
            this.Badges = Badges;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public QuestWinForm.ServiceReference1.AddUserResponseBody Body;
        
        public AddUserResponse() {
        }
        
        public AddUserResponse(QuestWinForm.ServiceReference1.AddUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddUserResponseBody {
        
        public AddUserResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowQuestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowQuest", Namespace="http://tempuri.org/", Order=0)]
        public QuestWinForm.ServiceReference1.ShowQuestRequestBody Body;
        
        public ShowQuestRequest() {
        }
        
        public ShowQuestRequest(QuestWinForm.ServiceReference1.ShowQuestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ShowQuestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public ShowQuestRequestBody() {
        }
        
        public ShowQuestRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowQuestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowQuestResponse", Namespace="http://tempuri.org/", Order=0)]
        public QuestWinForm.ServiceReference1.ShowQuestResponseBody Body;
        
        public ShowQuestResponse() {
        }
        
        public ShowQuestResponse(QuestWinForm.ServiceReference1.ShowQuestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ShowQuestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public QuestWinForm.ServiceReference1.ArrayOfString ShowQuestResult;
        
        public ShowQuestResponseBody() {
        }
        
        public ShowQuestResponseBody(QuestWinForm.ServiceReference1.ArrayOfString ShowQuestResult) {
            this.ShowQuestResult = ShowQuestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckUser", Namespace="http://tempuri.org/", Order=0)]
        public QuestWinForm.ServiceReference1.CheckUserRequestBody Body;
        
        public CheckUserRequest() {
        }
        
        public CheckUserRequest(QuestWinForm.ServiceReference1.CheckUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public CheckUserRequestBody() {
        }
        
        public CheckUserRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public QuestWinForm.ServiceReference1.CheckUserResponseBody Body;
        
        public CheckUserResponse() {
        }
        
        public CheckUserResponse(QuestWinForm.ServiceReference1.CheckUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int CheckUserResult;
        
        public CheckUserResponseBody() {
        }
        
        public CheckUserResponseBody(int CheckUserResult) {
            this.CheckUserResult = CheckUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowUser", Namespace="http://tempuri.org/", Order=0)]
        public QuestWinForm.ServiceReference1.ShowUserRequestBody Body;
        
        public ShowUserRequest() {
        }
        
        public ShowUserRequest(QuestWinForm.ServiceReference1.ShowUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ShowUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public ShowUserRequestBody() {
        }
        
        public ShowUserRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public QuestWinForm.ServiceReference1.ShowUserResponseBody Body;
        
        public ShowUserResponse() {
        }
        
        public ShowUserResponse(QuestWinForm.ServiceReference1.ShowUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ShowUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public QuestWinForm.ServiceReference1.ArrayOfString ShowUserResult;
        
        public ShowUserResponseBody() {
        }
        
        public ShowUserResponseBody(QuestWinForm.ServiceReference1.ArrayOfString ShowUserResult) {
            this.ShowUserResult = ShowUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowLeaderboardRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowLeaderboard", Namespace="http://tempuri.org/", Order=0)]
        public QuestWinForm.ServiceReference1.ShowLeaderboardRequestBody Body;
        
        public ShowLeaderboardRequest() {
        }
        
        public ShowLeaderboardRequest(QuestWinForm.ServiceReference1.ShowLeaderboardRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ShowLeaderboardRequestBody {
        
        public ShowLeaderboardRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowLeaderboardResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowLeaderboardResponse", Namespace="http://tempuri.org/", Order=0)]
        public QuestWinForm.ServiceReference1.ShowLeaderboardResponseBody Body;
        
        public ShowLeaderboardResponse() {
        }
        
        public ShowLeaderboardResponse(QuestWinForm.ServiceReference1.ShowLeaderboardResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ShowLeaderboardResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public QuestWinForm.ServiceReference1.ArrayOfString ShowLeaderboardResult;
        
        public ShowLeaderboardResponseBody() {
        }
        
        public ShowLeaderboardResponseBody(QuestWinForm.ServiceReference1.ArrayOfString ShowLeaderboardResult) {
            this.ShowLeaderboardResult = ShowLeaderboardResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowQuestBoardRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowQuestBoard", Namespace="http://tempuri.org/", Order=0)]
        public QuestWinForm.ServiceReference1.ShowQuestBoardRequestBody Body;
        
        public ShowQuestBoardRequest() {
        }
        
        public ShowQuestBoardRequest(QuestWinForm.ServiceReference1.ShowQuestBoardRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ShowQuestBoardRequestBody {
        
        public ShowQuestBoardRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowQuestBoardResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowQuestBoardResponse", Namespace="http://tempuri.org/", Order=0)]
        public QuestWinForm.ServiceReference1.ShowQuestBoardResponseBody Body;
        
        public ShowQuestBoardResponse() {
        }
        
        public ShowQuestBoardResponse(QuestWinForm.ServiceReference1.ShowQuestBoardResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ShowQuestBoardResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public QuestWinForm.ServiceReference1.ArrayOfString ShowQuestBoardResult;
        
        public ShowQuestBoardResponseBody() {
        }
        
        public ShowQuestBoardResponseBody(QuestWinForm.ServiceReference1.ArrayOfString ShowQuestBoardResult) {
            this.ShowQuestBoardResult = ShowQuestBoardResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface QuestWebServiceSoapChannel : QuestWinForm.ServiceReference1.QuestWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QuestWebServiceSoapClient : System.ServiceModel.ClientBase<QuestWinForm.ServiceReference1.QuestWebServiceSoap>, QuestWinForm.ServiceReference1.QuestWebServiceSoap {
        
        public QuestWebServiceSoapClient() {
        }
        
        public QuestWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QuestWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QuestWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QuestWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuestWinForm.ServiceReference1.AddQuestResponse QuestWinForm.ServiceReference1.QuestWebServiceSoap.AddQuest(QuestWinForm.ServiceReference1.AddQuestRequest request) {
            return base.Channel.AddQuest(request);
        }
        
        public void AddQuest(string Title, string Description, int Tokens, int Badges, int CreatorId) {
            QuestWinForm.ServiceReference1.AddQuestRequest inValue = new QuestWinForm.ServiceReference1.AddQuestRequest();
            inValue.Body = new QuestWinForm.ServiceReference1.AddQuestRequestBody();
            inValue.Body.Title = Title;
            inValue.Body.Description = Description;
            inValue.Body.Tokens = Tokens;
            inValue.Body.Badges = Badges;
            inValue.Body.CreatorId = CreatorId;
            QuestWinForm.ServiceReference1.AddQuestResponse retVal = ((QuestWinForm.ServiceReference1.QuestWebServiceSoap)(this)).AddQuest(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QuestWinForm.ServiceReference1.AddQuestResponse> QuestWinForm.ServiceReference1.QuestWebServiceSoap.AddQuestAsync(QuestWinForm.ServiceReference1.AddQuestRequest request) {
            return base.Channel.AddQuestAsync(request);
        }
        
        public System.Threading.Tasks.Task<QuestWinForm.ServiceReference1.AddQuestResponse> AddQuestAsync(string Title, string Description, int Tokens, int Badges, int CreatorId) {
            QuestWinForm.ServiceReference1.AddQuestRequest inValue = new QuestWinForm.ServiceReference1.AddQuestRequest();
            inValue.Body = new QuestWinForm.ServiceReference1.AddQuestRequestBody();
            inValue.Body.Title = Title;
            inValue.Body.Description = Description;
            inValue.Body.Tokens = Tokens;
            inValue.Body.Badges = Badges;
            inValue.Body.CreatorId = CreatorId;
            return ((QuestWinForm.ServiceReference1.QuestWebServiceSoap)(this)).AddQuestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuestWinForm.ServiceReference1.AddUserResponse QuestWinForm.ServiceReference1.QuestWebServiceSoap.AddUser(QuestWinForm.ServiceReference1.AddUserRequest request) {
            return base.Channel.AddUser(request);
        }
        
        public void AddUser(string Username, string Password, int Tokens, int Badges) {
            QuestWinForm.ServiceReference1.AddUserRequest inValue = new QuestWinForm.ServiceReference1.AddUserRequest();
            inValue.Body = new QuestWinForm.ServiceReference1.AddUserRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            inValue.Body.Tokens = Tokens;
            inValue.Body.Badges = Badges;
            QuestWinForm.ServiceReference1.AddUserResponse retVal = ((QuestWinForm.ServiceReference1.QuestWebServiceSoap)(this)).AddUser(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QuestWinForm.ServiceReference1.AddUserResponse> QuestWinForm.ServiceReference1.QuestWebServiceSoap.AddUserAsync(QuestWinForm.ServiceReference1.AddUserRequest request) {
            return base.Channel.AddUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<QuestWinForm.ServiceReference1.AddUserResponse> AddUserAsync(string Username, string Password, int Tokens, int Badges) {
            QuestWinForm.ServiceReference1.AddUserRequest inValue = new QuestWinForm.ServiceReference1.AddUserRequest();
            inValue.Body = new QuestWinForm.ServiceReference1.AddUserRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            inValue.Body.Tokens = Tokens;
            inValue.Body.Badges = Badges;
            return ((QuestWinForm.ServiceReference1.QuestWebServiceSoap)(this)).AddUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuestWinForm.ServiceReference1.ShowQuestResponse QuestWinForm.ServiceReference1.QuestWebServiceSoap.ShowQuest(QuestWinForm.ServiceReference1.ShowQuestRequest request) {
            return base.Channel.ShowQuest(request);
        }
        
        public QuestWinForm.ServiceReference1.ArrayOfString ShowQuest(int id) {
            QuestWinForm.ServiceReference1.ShowQuestRequest inValue = new QuestWinForm.ServiceReference1.ShowQuestRequest();
            inValue.Body = new QuestWinForm.ServiceReference1.ShowQuestRequestBody();
            inValue.Body.id = id;
            QuestWinForm.ServiceReference1.ShowQuestResponse retVal = ((QuestWinForm.ServiceReference1.QuestWebServiceSoap)(this)).ShowQuest(inValue);
            return retVal.Body.ShowQuestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QuestWinForm.ServiceReference1.ShowQuestResponse> QuestWinForm.ServiceReference1.QuestWebServiceSoap.ShowQuestAsync(QuestWinForm.ServiceReference1.ShowQuestRequest request) {
            return base.Channel.ShowQuestAsync(request);
        }
        
        public System.Threading.Tasks.Task<QuestWinForm.ServiceReference1.ShowQuestResponse> ShowQuestAsync(int id) {
            QuestWinForm.ServiceReference1.ShowQuestRequest inValue = new QuestWinForm.ServiceReference1.ShowQuestRequest();
            inValue.Body = new QuestWinForm.ServiceReference1.ShowQuestRequestBody();
            inValue.Body.id = id;
            return ((QuestWinForm.ServiceReference1.QuestWebServiceSoap)(this)).ShowQuestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuestWinForm.ServiceReference1.CheckUserResponse QuestWinForm.ServiceReference1.QuestWebServiceSoap.CheckUser(QuestWinForm.ServiceReference1.CheckUserRequest request) {
            return base.Channel.CheckUser(request);
        }
        
        public int CheckUser(string username, string password) {
            QuestWinForm.ServiceReference1.CheckUserRequest inValue = new QuestWinForm.ServiceReference1.CheckUserRequest();
            inValue.Body = new QuestWinForm.ServiceReference1.CheckUserRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            QuestWinForm.ServiceReference1.CheckUserResponse retVal = ((QuestWinForm.ServiceReference1.QuestWebServiceSoap)(this)).CheckUser(inValue);
            return retVal.Body.CheckUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QuestWinForm.ServiceReference1.CheckUserResponse> QuestWinForm.ServiceReference1.QuestWebServiceSoap.CheckUserAsync(QuestWinForm.ServiceReference1.CheckUserRequest request) {
            return base.Channel.CheckUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<QuestWinForm.ServiceReference1.CheckUserResponse> CheckUserAsync(string username, string password) {
            QuestWinForm.ServiceReference1.CheckUserRequest inValue = new QuestWinForm.ServiceReference1.CheckUserRequest();
            inValue.Body = new QuestWinForm.ServiceReference1.CheckUserRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((QuestWinForm.ServiceReference1.QuestWebServiceSoap)(this)).CheckUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuestWinForm.ServiceReference1.ShowUserResponse QuestWinForm.ServiceReference1.QuestWebServiceSoap.ShowUser(QuestWinForm.ServiceReference1.ShowUserRequest request) {
            return base.Channel.ShowUser(request);
        }
        
        public QuestWinForm.ServiceReference1.ArrayOfString ShowUser(int id) {
            QuestWinForm.ServiceReference1.ShowUserRequest inValue = new QuestWinForm.ServiceReference1.ShowUserRequest();
            inValue.Body = new QuestWinForm.ServiceReference1.ShowUserRequestBody();
            inValue.Body.id = id;
            QuestWinForm.ServiceReference1.ShowUserResponse retVal = ((QuestWinForm.ServiceReference1.QuestWebServiceSoap)(this)).ShowUser(inValue);
            return retVal.Body.ShowUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QuestWinForm.ServiceReference1.ShowUserResponse> QuestWinForm.ServiceReference1.QuestWebServiceSoap.ShowUserAsync(QuestWinForm.ServiceReference1.ShowUserRequest request) {
            return base.Channel.ShowUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<QuestWinForm.ServiceReference1.ShowUserResponse> ShowUserAsync(int id) {
            QuestWinForm.ServiceReference1.ShowUserRequest inValue = new QuestWinForm.ServiceReference1.ShowUserRequest();
            inValue.Body = new QuestWinForm.ServiceReference1.ShowUserRequestBody();
            inValue.Body.id = id;
            return ((QuestWinForm.ServiceReference1.QuestWebServiceSoap)(this)).ShowUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuestWinForm.ServiceReference1.ShowLeaderboardResponse QuestWinForm.ServiceReference1.QuestWebServiceSoap.ShowLeaderboard(QuestWinForm.ServiceReference1.ShowLeaderboardRequest request) {
            return base.Channel.ShowLeaderboard(request);
        }
        
        public QuestWinForm.ServiceReference1.ArrayOfString ShowLeaderboard() {
            QuestWinForm.ServiceReference1.ShowLeaderboardRequest inValue = new QuestWinForm.ServiceReference1.ShowLeaderboardRequest();
            inValue.Body = new QuestWinForm.ServiceReference1.ShowLeaderboardRequestBody();
            QuestWinForm.ServiceReference1.ShowLeaderboardResponse retVal = ((QuestWinForm.ServiceReference1.QuestWebServiceSoap)(this)).ShowLeaderboard(inValue);
            return retVal.Body.ShowLeaderboardResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QuestWinForm.ServiceReference1.ShowLeaderboardResponse> QuestWinForm.ServiceReference1.QuestWebServiceSoap.ShowLeaderboardAsync(QuestWinForm.ServiceReference1.ShowLeaderboardRequest request) {
            return base.Channel.ShowLeaderboardAsync(request);
        }
        
        public System.Threading.Tasks.Task<QuestWinForm.ServiceReference1.ShowLeaderboardResponse> ShowLeaderboardAsync() {
            QuestWinForm.ServiceReference1.ShowLeaderboardRequest inValue = new QuestWinForm.ServiceReference1.ShowLeaderboardRequest();
            inValue.Body = new QuestWinForm.ServiceReference1.ShowLeaderboardRequestBody();
            return ((QuestWinForm.ServiceReference1.QuestWebServiceSoap)(this)).ShowLeaderboardAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuestWinForm.ServiceReference1.ShowQuestBoardResponse QuestWinForm.ServiceReference1.QuestWebServiceSoap.ShowQuestBoard(QuestWinForm.ServiceReference1.ShowQuestBoardRequest request) {
            return base.Channel.ShowQuestBoard(request);
        }
        
        public QuestWinForm.ServiceReference1.ArrayOfString ShowQuestBoard() {
            QuestWinForm.ServiceReference1.ShowQuestBoardRequest inValue = new QuestWinForm.ServiceReference1.ShowQuestBoardRequest();
            inValue.Body = new QuestWinForm.ServiceReference1.ShowQuestBoardRequestBody();
            QuestWinForm.ServiceReference1.ShowQuestBoardResponse retVal = ((QuestWinForm.ServiceReference1.QuestWebServiceSoap)(this)).ShowQuestBoard(inValue);
            return retVal.Body.ShowQuestBoardResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QuestWinForm.ServiceReference1.ShowQuestBoardResponse> QuestWinForm.ServiceReference1.QuestWebServiceSoap.ShowQuestBoardAsync(QuestWinForm.ServiceReference1.ShowQuestBoardRequest request) {
            return base.Channel.ShowQuestBoardAsync(request);
        }
        
        public System.Threading.Tasks.Task<QuestWinForm.ServiceReference1.ShowQuestBoardResponse> ShowQuestBoardAsync() {
            QuestWinForm.ServiceReference1.ShowQuestBoardRequest inValue = new QuestWinForm.ServiceReference1.ShowQuestBoardRequest();
            inValue.Body = new QuestWinForm.ServiceReference1.ShowQuestBoardRequestBody();
            return ((QuestWinForm.ServiceReference1.QuestWebServiceSoap)(this)).ShowQuestBoardAsync(inValue);
        }
        
        public void AcceptQuest(int id) {
            base.Channel.AcceptQuest(id);
        }
        
        public System.Threading.Tasks.Task AcceptQuestAsync(int id) {
            return base.Channel.AcceptQuestAsync(id);
        }
        
        public void Reward(int id, int tokens, int badges) {
            base.Channel.Reward(id, tokens, badges);
        }
        
        public System.Threading.Tasks.Task RewardAsync(int id, int tokens, int badges) {
            return base.Channel.RewardAsync(id, tokens, badges);
        }
    }
}
